In [ ]:
import numpy as np

X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])
y = np.array([[0,1,1,0]]).T


In [ ]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [ ]:
y

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for _ in range(2000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [ ]:
l2

array([[0.03234525],
       [0.97725885],
       [0.96450169],
       [0.03162243]])

In [ ]:
syn1

array([[-2.50968999],
       [ 7.39299465],
       [-8.75343507],
       [ 6.87200485]])

In [ ]:
import tensorflow as tf

model = tf.keras.Sequential([
        tf.keras.layers.Dense(4, activation='sigmoid', input_shape=(3,)),# 4,3 -> 4,4
        tf.keras.layers.Dense(1, activation='sigmoid')]) # 4,4 -> 4,1

model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=1.), loss='mean_squared_error')
model.fit(X, y, epochs=1000, verbose=0)
model.predict(X)




/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step


array([[0.08313257],
       [0.8824642 ],
       [0.8658438 ],
       [0.15516032]], dtype=float32)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

x_data = torch.tensor(X, dtype=torch.float32)
y_data = torch.tensor(y, dtype=torch.float32)

class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        self.fc1 = nn.Linear(3, 4)
        self.fc2 = nn.Linear(4, 1)
        self.sigmoid = nn.Sigmoid()
    def forward(self, x):
        x = self.sigmoid(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

model = XORModel()
optimizer = optim.SGD(model.parameters(), lr=1.)
criterion = nn.MSELoss()
# Train the model
for epoch in range(4000):
    optimizer.zero_grad()
    output = model(x_data)
    loss = criterion(output, y_data)
    print(loss)
    loss.backward()
    optimizer.step()

# Test the model
predictions = model(x_data).detach().numpy()
rounded_predictions = np.round(predictions)

print('Predictions:')
for i in range(len(x_data)):
    print(x_data[i].numpy(),  predictions[i])

In [ ]:
# https://towardsdatascience.com/three-ways-to-build-a-neural-network-in-pytorch-8cea49f9a61a
###########
model = nn.Sequential(
    nn.Linear(16, 12),
    nn.ReLU(),
    nn.Linear(12, 10),
    nn.ReLU(),
    nn.Linear(10, 1),
    nn.Sigmoid()
)
###########
class MyNetwork(nn.Module):
    def __init__(self):
        # call constructor from superclass
        super().__init__()

        # define network layers
        self.fc1 = nn.Linear(16, 12)
        self.fc2 = nn.Linear(12, 10)
        self.fc3 = nn.Linear(10, 1)

    def forward(self, x):
        # define forward pass
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x
#########
features = torch.randn(1, 16)

W1 = torch.randn((16, 12), requires_grad=True)
W2 = torch.randn((12, 10), requires_grad=True)
W3 = torch.randn((10, 1), requires_grad=True)

B1 = torch.randn((12), requires_grad=True)
B2 = torch.randn((10), requires_grad=True)
B3 = torch.randn((1), requires_grad=True)

h1 = F.relu((features @ W1) + B1)
h2 = F.relu((h1 @ W2) + B2)
output = torch.sigmoid((h2 @ W3) + B3)

#######

https://github.com/google-research/tuning_playbook/blob/main/README.md#choosing-the-optimizer

https://github.com/google-research/tuning_playbook

In [ ]:
import torch
x, y = torch.tensor(np.array([ [0.,0.,1.],[0.,1.,1.],[1.,0.,1.],[1.,1.,1.] ])),  torch.tensor(np.array([[0.,1.,1.,0.]]).T)
#X = torch.tensor(X)
#y = torch.tensor(y)

w = torch.tensor(np.array([.1,.1,.1]), requires_grad=True)
loss = (((w*x)-y)**2)
loss.backward()

with torch.no_grad():
  w -= w.grad * .1

By:

Joaquin Dominguez(https://www.linkedin.com/in/joaquin-dominguez1992/)

Richard Kim(https://www.linkedin.com/in/richard-y-kim/)

John Santerre(https://www.linkedin.com/in/john-santerre-phd-91609b6/)

